##
 # This file is part of the Toggler package.
 #
 # (c) SolidWorx <open-source@solidworx.co>
 #
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 ##

services:
    _defaults:
        autowire: true
        autoconfigure: true

    SolidWorx\Toggler\Symfony\Command\:
        resource: '../../Command/'

    SolidWorx\Toggler\Symfony\Command\ToggleSetCommand:
        arguments: ['?']

    SolidWorx\Toggler\Symfony\Command\ToggleGetCommand:
        arguments:
            $toggle: '@SolidWorx\Toggler\Toggle'

    SolidWorx\Toggler\Symfony\Command\ToggleListCommand:
        arguments:
            $toggle: '@SolidWorx\Toggler\Toggle'
            $toggleStorage: '@toggler.storage'

    toggler.expression.language.provider.dependency_injection:
        class: Symfony\Component\DependencyInjection\ExpressionLanguageProvider
        public: false

    toggler.expression.language.provider.security:
        class: Symfony\Component\Security\Core\Authorization\ExpressionLanguageProvider
        public: false

    toggler.expression.language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
        public: false
        calls:
            - ['registerProvider', ['@toggler.expression.language.provider.security']]

    SolidWorx\Toggler\Toggle:
        arguments: ['?', '@toggler.expression.language']

    SolidWorx\Toggler\ToggleInterface: '@SolidWorx\Toggler\Toggle'

    SolidWorx\Toggler\Symfony\Toggle:
        decorates: 'SolidWorx\Toggler\Toggle'
        public: false
        arguments:
            $toggle: '@SolidWorx\Toggler\Symfony\Toggle.inner'
            $roleHierarchy: '@security.role_hierarchy'
            $trustResolver: '@security.authentication.trust_resolver'

    SolidWorx\Toggler\Twig\Extension\ToggleExtension:
        arguments: ['@SolidWorx\Toggler\Toggle']
        tags:
            - { name: twig.extension }
