name: Toggler Test Suite

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        dependencies: [lowest, highest]
        include:
          - php: 8.4
            coverage: true

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${ matrix.coverage && 'xdebug' || 'none' }

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
            dependency-versions: "${{ matrix.dependencies }}"

      - name: Run test suite
        run: |
            ${{ matrix.coverage && 'vendor/bin/phpunit --coverage-clover build/logs/clover.xml' || 'vendor/bin/phpunit' }}

      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/clover.xml
          fail_ci_if_error: true
          verbose: true
