name: "PHPStan"

on:
  push:
    branches:
      - 'master'
  pull_request: ~

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-"

      - name: "Install dependencies"
        run: "composer update"

      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit --version

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon
